[pytest]
pythonpath = .
markers =
    registration: тесты функциональности регистрации
    login: тесты функциональности авторизации
    recipe: тесты функциональности создания рецепта
addopts = -v --alluredir=allure-results
